PADV-523 - Making ecommerce MFEs optional.
Pearson-Advance/tutor-ecommerce pull request #5
Opened 2023-06-06 01:13 UTC by Squirrel18

## Description:

This PR adds the possibility to disable the ecommerce MFEs.

## Test:

- Add these overwrite to a Tutor plugin: `"ECOMMERCE_PAYMENT_MFE_APP": None, "ECOMMERCE_MFE_APP": None,`
- Run tutor config save.
- Check that the MFEs Dockerfile is rendered without these MFEs.

## Reviewers:

- [ ] @Jacatove 
- [ ] @kuipumu

2023-06-06 20:34 UTC, Jacatove requested changes
Nice!

2023-06-06 20:34 UTC, Jacatove commented on tutorecommerce/patches/openedx-lms-development-settings
> +{% endif %}
We really don't use development files. @Squirrel18 
```suggestion
```

2023-06-06 20:34 UTC, Jacatove commented on tutorecommerce/patches/openedx-lms-production-settings
> +{% endif %}
This will cause indentation issues. @Squirrel18 

![image](https://github.com/Pearson-Advance/tutor-ecommerce/assets/40271196/449f41dc-a2a0-4461-8e2a-86e96646af19)

```suggestion
{% if ECOMMERCE_MFE_APP %}
ORDER_HISTORY_MICROFRONTEND_URL = "{% if ENABLE_HTTPS %}https{% else %}http{% endif %}://{{ MFE_HOST }}/{{ ECOMMERCE_MFE_APP['name'] }}/orders"
{% endif %}
```

2023-06-06 20:34 UTC, Jacatove commented on tutorecommerce/templates/ecommerce/apps/ecommerce/settings/development.py
> +    CSRF_TRUSTED_ORIGINS = ["{{ MFE_HOST }}:{{ ECOMMERCE_MFE_APP['port'] }}"]
Identation issues. @Squirrel18 
```suggestion
CORS_ORIGIN_WHITELIST = list(CORS_ORIGIN_WHITELIST) + [
    "http://{{ MFE_HOST }}:{{ ECOMMERCE_MFE_APP['port'] }}",
    "http://{{ MFE_HOST }}:{{ ECOMMERCE_PAYMENT_MFE_APP['port'] }}",
]
CSRF_TRUSTED_ORIGINS = ["{{ MFE_HOST }}:{{ ECOMMERCE_MFE_APP['port'] }}"]
```

2023-06-07 03:35 UTC, Jacatove requested changes

2023-06-07 03:35 UTC, Jacatove commented on tutorecommerce/patches/openedx-lms-development-settings
> +{% endif %}
@Squirrel18 Could you please remove the conditional or fix identation?

2023-06-07 15:29 UTC, Jacatove requested changes

2023-06-07 15:29 UTC, Jacatove commented on tutorecommerce/patches/openedx-lms-production-settings
>  MFE_CONFIG["ORDER_HISTORY_URL"] = ORDER_HISTORY_MICROFRONTEND_URL
@Squirrel18  Sorry I didnt see this undefined issue before..

![image](https://github.com/Pearson-Advance/tutor-ecommerce/assets/40271196/c0b60cec-fa26-469c-a4d1-394258250b73)

```suggestion
MFE_CONFIG["ORDER_HISTORY_URL"] = ""
{% if ECOMMERCE_MFE_APP %}
ORDER_HISTORY_MICROFRONTEND_URL = "{% if ENABLE_HTTPS %}https{% else %}http{% endif %}://{{ MFE_HOST }}/{{ ECOMMERCE_MFE_APP['name'] }}/orders"
MFE_CONFIG["ORDER_HISTORY_URL"] = ORDER_HISTORY_MICROFRONTEND_URL
{% endif %}
MFE_CONFIG["ECOMMERCE_BASE_URL"] = ECOMMERCE_PUBLIC_URL_ROOT
```

2023-06-07 16:00 UTC, Jacatove approved these changes

2023-06-07 16:46 UTC, kuipumu approved these changes

2023-06-09 21:48 UTC, kuipumu commented on tutorecommerce/patches/openedx-lms-production-settings
>  MFE_CONFIG["ORDER_HISTORY_URL"] = ORDER_HISTORY_MICROFRONTEND_URL
```suggestion
MFE_CONFIG["ORDER_HISTORY_URL"] = ORDER_HISTORY_MICROFRONTEND_URL
MFE_CONFIG["ECOMMERCE_BASE_URL"] = ECOMMERCE_PUBLIC_URL_ROOT
```

2023-06-09 22:13 UTC, kuipumu approved these changes

2023-06-09 22:36 UTC, merged